apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: condor-scaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Object
    object:
      metric:
        name: condor_slot_activity_busy
      describedObject:
        apiVersion: batch/v1
        kind: Job
        name: kubernetes-pods
      target:
        type: Value
        value: 0.9
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 
