apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: condor-scaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
#      policies:
#      - type: Object
#        object:
#          metric:
#            name: condor_slot_activity_busy_single
#          describedObject:
#            apiVersion: batch/v1
#            kind: Job
#            name: kubernetes-pods   
        
