apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      receiver: 'slack-notifications'
      routes:
        - match:
            severity: page
          continue: true
          receiver: 'slack-notifications'
        - match:
            severity: page
          receiver: 'gmail-notifications'

    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#k3shtc'
        send_resolved: true
    - name: 'gmail-notifications'
      email_configs:
      - to: ahmadkhansa95@gmail.com
        from: k3shtc@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: k3shtc@gmail.com
        auth_identity: k3shtc@gmail.com
        auth_password: yonrkygcxyfhvjgi
        send_resolved: true

