apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      slack_api_url: 'slack webhook'

    route:
      receiver: 'slack-notifications'
      routes:
        - match:
            severity: page
          continue: true
          receiver: 'slack-notifications'
        - match:
            severity: page
          receiver: 'gmail-notifications'

    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#k3shtc'
        send_resolved: true
    - name: 'gmail-notifications'
      email_configs:
      - to: <reciever email address>
        from: <sender email address>
        smarthost: <gmail smarthost>
        auth_username: <sender email address>
        auth_identity: <sender email address>
        auth_password: <sender password>
        send_resolved: true

