kind: Service
apiVersion: v1
metadata:
  name: alertmanager
spec:
  selector:
    app: alertmanager
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 9093
    nodePort: 30910

