# schedd deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: condor-notebook
  labels:
    name: condor-notebook
spec:
  selector:
    matchLabels:
      app: condor-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: condor-notebook
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k3s.io/hostname
                operator: In
                values:
                - k3s-htc.novalocal 
      containers:
      - name: schedd-notebook
        imagePullPolicy: Always
        image: "htcondor/htc-base-notebook"
        volumeMounts:
          - mountPath: "/etc/condor/condor_config.local"
            name: condor-notebook
            subPath: condor_config.local
        ports:
        - containerPort: 9618
        - containerPort: 8888
      volumes:
      - name: condor-notebook
        configMap:
          name: condor-notebook

