# master configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: master
data:
  51-role-cm: |
    CONDOR_HOST = master.default.svc.cluster.local
    DAEMON_LIST = MASTER, COLLECTOR, NEGOTIATOR
    # use ROLE: CentralManager
    # ALLOW_WRITE_COLLECTOR=\$(ALLOW_WRITE) schedd.default.svc.cluster.local worker.default.svc.cluster.local
    # USED_SHARED_PORT = TRUE
    # SHARED_PORT_ARGS = -p 9618

  security: |
    SEC_DEFAULT_AUTHENTICATION = OPTIONAL
    SEC_READ_AUTHENTICATION = OPTIONAL
    SEC_WRITE_AUTHENTICATION = OPTIONAL
    SEC_ADMINISTRATOR_AUTHENTICATION = OPTIONAL
    SEC_CONFIG_AUTHENTICATION = OPTIONAL
    SEC_OWNER_AUTHENTICATION = OPTIONAL
    SEC_DAEMON_AUTHENTICATION = OPTIONAL
    SEC_NEGOTIATOR_AUTHENTICATION = OPTIONAL
    SEC_ADVERTISE_MASTER_AUTHENTICATION = OPTIONAL
    SEC_ADVERTISE_STARTD_AUTHENTICATION = OPTIONAL
    SEC_ADVERTISE_SCHEDD_AUTHENTICATION = OPTIONAL
    SEC_DEFAULT_INTEGRITY = OPTIONAL
    SEC_READ_INTEGRITY = OPTIONAL
    SEC_WRITE_INTEGRITY = OPTIONAL
    SEC_ADMINISTRATOR_INTEGRITY = OPTIONAL
    SEC_CONFIG_INTEGRITY = OPTIONAL
    SEC_OWNER_INTEGRITY = OPTIONAL
    SEC_DAEMON_INTEGRITY = OPTIONAL
    SEC_NEGOTIATOR_INTEGRITY = OPTIONAL
    SEC_ADVERTISE_MASTER_INTEGRITY = OPTIONAL
    SEC_ADVERTISE_STARTD_INTEGRITY = OPTIONAL
    SEC_ADVERTISE_SCHEDD_INTEGRITY = OPTIONAL
    SEC_DEFAULT_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_READ_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_WRITE_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_ADMINISTRATOR_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_CONFIG_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_OWNER_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_DAEMON_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_NEGOTIATOR_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_ADVERTISE_MASTER_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_ADVERTISE_STARTD_AUTHENTICATION_METHODS = CLAIMTOBE
    SEC_ADVERTISE_SCHEDD_AUTHENTICATION_METHODS = CLAIMTOBE

  authorization: |
    ALLOW_DAEMON = *
    # ALLOW_NEGOTIATOR = condor_pool@*/master.default.svc.cluster.local
    ALLOW_ADMINISTRATOR = *
    ALLOW_OWNER = *
    ALLOW_READ = *
    ALLOW_WRITE = *
    ALLOW_NEGOTIATOR = *
    ALLOW_NEGOTIATOR_SCHEDD = *
    ALLOW_WRITE_COLLECTOR = *
    ALLOW_WRITE_STARTD    = *
    ALLOW_READ_COLLECTOR  = *
    ALLOW_READ_STARTD     = *
    HOSTALLOW_READ_SCHEDD = *
    HOSTALLOW_WRITE_SCHEDD = *
  policy: |
    #Disable preemption by machine activity.
    PREEMPT = False
    #Disable preemption by user priority.
    PREEMPTION_REQUIREMENTS = False
    #Disable preemption by machine RANK by ranking all jobs equally.
    RANK = 0
    #Since we are disabling claim preemption, we
    # may as well optimize negotiation for this case:
    NEGOTIATOR_CONSIDER_PREEMPTION = False
