# persistent volume claim for execution file
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: condor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
