apiVersion: v1
kind: PersistentVolume
metadata:
  name: sing-images
spec:
  capacity:
    storage: 60Gi
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  nfs:
    path: <path to the directory containing singularity images>
    server: <IP address of the NFS server>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sing-images
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 60Gi
