# chedd deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedd
  labels:
    name: schedd
spec:
  selector:
    matchLabels:
      app: schedd
  replicas: 1
  template:
    metadata:
      labels:
        app: schedd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k3s.io/hostname
                operator: In
                values:
                - k3s-htc.novalocal 
      containers:
      - name: schedd
        imagePullPolicy: Always
        image: "htcondor/base:8.9.7-el7"
        volumeMounts:
          - mountPath: "/etc/condor/config.d/" # 51-role-submit
            name: schedd
        ports:
        - containerPort: 9618
      volumes:
      - name: schedd
        configMap:
          name: schedd
