# headless master svc
apiVersion: v1
kind: Service
metadata:
  name: schedd-exporter
spec:
  clusterIP: None
  selector:
    app: schedd-exporter
  ports:
  - name: schedd-part
    port: 9618
    targetPort: 9618
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: schedd-exporter-metrics
spec:
  type: NodePort
  selector:
    app: schedd-exporter
  ports:
  - name: condor-exporter
    port: 9118
    targetPort: 9118
    protocol: TCP
    nodePort: 32747
