# schedd deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedd-exporter
  labels:
    name: schedd-exporter
spec:
  selector:
    matchLabels:
      app: schedd-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: schedd-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-htc.novalocal 
      containers:
      - name: schedd-exporter
        imagePullPolicy: Always
        image: "2281995/htc-schedd-exporter"
        volumeMounts:
          - mountPath: "/etc/condor/config.d/" #51-role-submit
            name: schedd
        ports:
        - containerPort: 9618
        - containerPort: 9118
      volumes:
      - name: schedd
        configMap:
          name: schedd
