# worker deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k3s.io/hostname
                operator: In
                values:
                - k3s-htc-clust.novalocal 
      containers:
      - name: worker
        imagePullPolicy: Always
        image: "2281995/worker-docker"
        volumeMounts:
          - mountPath: "/etc/condor/config.d/"
            name: worker
          - mountPath: /var/run/docker.sock
            name: docker-socket
            readOnly: false
          - mountPath: /var/lib/condor/execute
            name: condor-executions
            readOnly: false
        ports:
        - containerPort: 9618
        securityContext:
          privileged: true
      volumes:
      - name: worker
        configMap:
          name: worker
      - name: docker-socket
        hostPath:
          path: "/var/run/docker.sock"
      - name: condor-executions
        hostPath:
          path: "/var/lib/condor/execute"
          type: Directory
